sudo: false
language: python
python:
- '2.7'
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install python-coveralls
script:
- pycodestyle --exclude=uw_canvas/tests uw_canvas
- coverage run uw_canvas/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_canvas/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_canvas/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: YsKR2f+st4OqJp+oZJrR0AUcHgf7ZjgaeyTF8w1+xFCteWMIlWeRrLzgJb6KiwfArd+WMSZ4xgqzbqNkp+pCaJ/gtOQpou94P0mwrnHwBd6/j4wrZYzNL3mNaFSTfMbhG0p5xaX92IOnn82bo+f3t9UATZekmHnrj/OMLXiqG6Lki0CVc8Uv23shNIVy6YuxCgOB0wafqXL9CbqUKVs3yQHQ9koF0WvpNpg6rHbJCVGK3TD0xG7hy42uZGmutiot6Lc9Jw9hIfGMkQJ+2IUlKDeU6Xs6NqIxXNZZ8G3O4YIpdBuQxtxTACG7EMbiUOW3UsL7/AOjsfa7NjkMcwAp4aU3JIxvHPEE3S4kyzd3mZImPrbYsxlXXZdhDXsELMwOLZf+vbjrugz6pQc4rUlwbmpduKUH70EH1Hm4Ve+3THrHYNSMgAFNKkpjNn73PxXt/dKEUCpFlJxCxksHITt00vRiUCgwuEgBDPE4gaL/UHqc6EDCkqYVldrlsFIf79Vnhgzm1MlAYw125gN8Z+z/ssimUK1yOBv1s0LUxvfLGLLjRh8pu2ZnYLEMUqYvaUDhMQ1FnGn5YRhO3hfefnvudC4eUluFdQggzmcHcclAt87Gz2FVD0vZdu7FtgfSnBhCRhLNgt/VNf3hHuXrHsDH6gSZWN33bxLFFwngWMkli1w=
  on:
    tags: true
    python: '3.6'
